# Generated by Django 5.1.3 on 2024-12-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_task_based',
            field=models.BooleanField(default=False),
        ),
    ]
