# Generated by Django 5.1.3 on 2024-12-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lesson_is_task_based'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
