# Generated by Django 5.1.3 on 2024-12-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_lesson_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='points',
        ),
        migrations.AddField(
            model_name='quiz',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
