# Generated by Django 5.1.3 on 2024-12-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_task'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='completed_tasks',
            field=models.ManyToManyField(blank=True, to='lessons.task'),
        ),
    ]
