# Generated by Django 5.1.3 on 2024-12-22 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_task'),
        ('users', '0002_userprogress_completed_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('attempts', models.IntegerField(default=1)),
                ('passed', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.task')),
                ('user_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprogress')),
            ],
        ),
    ]
