# Generated by Django 5.1.3 on 2024-12-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_score_quizattempt_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='taskattempt',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
