# Generated by Django 5.1.3 on 2024-12-27 21:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_quizattempt_points_alter_taskattempt_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='taskattempt',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
